### ISSUE TITLE
bee run 遇到cannot find package 问题请教您

### ISSUE THREAD

**Issue by zhang12c** [yangfei4913438/goApiServer#3]
您好，我是一名新人，请教您这个问题是要怎么解决呢？
0003 Failed to build the application: lang/lang_error.go:5:2: cannot find package "rs-server/tools" in any of:
/usr/lib/go/src/rs-server/tools (from $GOROOT)

**Comment by yangfei4913438** [comment]
很抱歉，我是锅，我稍后检测一遍。这个是一个bug

**Comment by yangfei4913438** [comment]
已经修复了这个问题。
